name: sainapse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  
  # Camera and AWS dependencies
  camera: ^0.10.5+9
  
  # AWS SDK for Flutter
  dio: ^5.3.2
  crypto: ^3.0.3  # For AWS signing
  
  # UI Dependencies
  google_fonts: ^6.2.1

  image_picker: ^1.1.2
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  speech_to_text: ^7.0.0
  confetti: ^0.7.0
  qr_flutter: ^4.0.0
  lottie: ^2.7.0
  barcode_widget: ^2.0.4
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.1.0
  permission_handler: ^12.0.0+1
  flutter_tts: ^3.8.5
  model_viewer_plus: ^1.9.3
  provider: ^6.1.5
  intl: ^0.20.2
  graphview: ^1.2.0
  curved_navigation_bar: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/rewards.png
    - assets/human_heart.glb
    - assets/heart.jpg
    - assets/human_heart.glb
    - .env



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/test.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

